
spring:
  application:
    name: gatewayServer

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BOOKINGSERVICE
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/api/bookings/**

        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/api/payments/**

        - id: CATEGORYSERVICE
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/api/categories/**, /api/category/**

        - id: SALONSERVICE
          uri: lb://SALONSERVICE
          predicates:
            - Path=/api/salons/**

        - id: SERVICEOFFERING
          uri: lb://SERVICEOFFERING
          predicates:
            - Path=/api/service-offering/**

#        - id: USERSERVICE
#          uri: lb://USERSERVICE
#          predicates:
#            - Path=/api/users/**, /auth/**, /api/admin/users/**, /users/**

        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**
            - Path=/auth/**
            - Path=/api/admin/users/**
            - Path=/users/**








    security:
      oauth2:
        client:
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8088/eureka
stripe:
  api:
    key: ${STRIPE_KEY:stripe}
